#!/bin/sh
#
# mktrampolines: build the static clang and xstatic trampolines
# by pts@fazekas.hu at Thu Dec 26 17:45:15 CET 2013
#
# Run this script on an i386 or amd64 Linux.
#
# Here is how lib0.a was created from libc.a in musl-0.9.15:
#
# # TODO(pts): Come up with smaller, without pthread:
# $ rm -f ../lib0.a &&
#   ar cr ../lib0.a execv.o strcmp.o strncmp.o strstr.o strchr.o memchr.o \
#   memcmp.o execve.o __environ.o syscall_ret.o __errno_location.o libc.o \
#   syscall.o malloc.o stat.o memcpy.o mremap.o mmap.o __brk.o __wait.o \
#   munmap.o madvise.o internal_syscall.o strchrnul.o strlen.o \
#   __libc_start_main.o exit.o strcpy.o strcat.o lstat.o strdup.o getenv.o \
#   write.o readlink.o syscall_cp.o stpcpy.o cancel_impl.o pthread_kill.o \
#   __lock.o pthread_self.o sigfillset.o __set_thread_area.o sigaction.o \
#   restore.o pthread_sigmask.o _Exit.o pthread_create.o mprotect.o clone.o \
#   block.o __init_tls.o __unmapself.o __init_security.o waitpid.o fork.o \
#   unlink.o close.o read.o open.o uname.o memset.o

set -ex

test -f musllibc/lib0.a
test -f musllibc/crt1.o
test -f musllibc/miniinc.h
CFLAGS='-m32 -fno-stack-protector -fomit-frame-pointer -mpreferred-stack-boundary=2 -falign-functions=1 -falign-jumps=1 -falign-loops=1 -Os -W -Wall -Werror=implicit -Werror=implicit-int -Werror=implicit-function-declaration --sysroot musllibc -isystem musllibc -static-libgcc -DUSE_MINIINC'
LDFLAGS1='-nostdlib -m elf_i386 -static -s musllibc/crt1.o musllibc/crti.o musllibc/crtbeginT.o'
LDFLAGS2='musllibc/lib0.a musllibc/crtend.o musllibc/crtn.o'
STRIP='strip -S --strip-unneeded --remove-section=.note.gnu.gold-version --remove-section=.comment --remove-section=.note --remove-section=.note.gnu.build-id'

gcc $CFLAGS -c xstatic.c
ld -o xstatic $LDFLAGS1 xstatic.o $LDFLAGS2
$STRIP xstatic
gcc $CFLAGS -c clang_trampoline.c
ld -o clang $LDFLAGS1 clang_trampoline.o $LDFLAGS2
$STRIP clang
ls -l xstatic clang

: mktrampolines OK.
